# Generated by Django 3.1.1 on 2020-09-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='사용자명')),
                ('password', models.CharField(max_length=64, verbose_name='비밀번호')),
            ],
            options={
                'verbose_name': 'MLS_user',
                'verbose_name_plural': 'MLS_user',
                'db_table': 'MLS_user',
            },
        ),
    ]
