# Generated by Django 3.1.2 on 2020-10-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0002_timer_study_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timer',
            name='study_time',
        ),
        migrations.AddField(
            model_name='timer',
            name='study_hour',
            field=models.IntegerField(default=0, verbose_name='시간'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timer',
            name='study_min',
            field=models.IntegerField(default=2, verbose_name='분'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timer',
            name='study_sec',
            field=models.IntegerField(default=3, verbose_name='초'),
            preserve_default=False,
        ),
    ]
